### ISSUE TITLE
core-suggest: IE11 error

### ISSUE THREAD

**Issue by laat** [nrkno/core-components#347]
```
TypeError: Argument not optional
    at iterator (webpack:///node_modules/@nrk/core-suggest/core-suggest.cjs.js:420:8)
    at Anonymous function (webpack:///node_modules/@nrk/core-suggest/core-suggest.cjs.js:289:8)
```
https://github.com/nrkno/core-components/blob/3355e8ed773a5adc9f037ebf0a14f42eb3faed6f/packages/core-suggest/core-suggest.js#L98

Får en del slike feil i produksjons-loggene, hadde vært digg å få fjernet dem :)

Internet Explorer 11.0, Windows 7, 10

**Comment by laat** [comment]
jeg tror ikke det fører til feil hos brukere, har ikke fått noen melding om det.
